/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatIsBiRouteImport } from './routes/what-is-bi'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ExampleDashboardRouteImport } from './routes/example-dashboard'
import { Route as IndexRouteImport } from './routes/index'

const WhatIsBiRoute = WhatIsBiRouteImport.update({
  id: '/what-is-bi',
  path: '/what-is-bi',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ExampleDashboardRoute = ExampleDashboardRouteImport.update({
  id: '/example-dashboard',
  path: '/example-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/example-dashboard': typeof ExampleDashboardRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/what-is-bi': typeof WhatIsBiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/example-dashboard': typeof ExampleDashboardRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/what-is-bi': typeof WhatIsBiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/example-dashboard': typeof ExampleDashboardRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/what-is-bi': typeof WhatIsBiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/example-dashboard'
    | '/pricing'
    | '/sitemap.xml'
    | '/what-is-bi'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/example-dashboard' | '/pricing' | '/sitemap.xml' | '/what-is-bi'
  id:
    | '__root__'
    | '/'
    | '/example-dashboard'
    | '/pricing'
    | '/sitemap.xml'
    | '/what-is-bi'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExampleDashboardRoute: typeof ExampleDashboardRoute
  PricingRoute: typeof PricingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WhatIsBiRoute: typeof WhatIsBiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/what-is-bi': {
      id: '/what-is-bi'
      path: '/what-is-bi'
      fullPath: '/what-is-bi'
      preLoaderRoute: typeof WhatIsBiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/example-dashboard': {
      id: '/example-dashboard'
      path: '/example-dashboard'
      fullPath: '/example-dashboard'
      preLoaderRoute: typeof ExampleDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExampleDashboardRoute: ExampleDashboardRoute,
  PricingRoute: PricingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WhatIsBiRoute: WhatIsBiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
